"-D=AE_PROJECT_VERSION \"1.0.0\""
"-D=USER_CONFIG \"config/user_config_optimized.h\""
"-D=FS_INIT \"config/file_system_init.h\""
"-ffast-math"
"-fno-math-errno"
"-funsafe-math-optimizations"
"-fassociative-math"
"-freciprocal-math"
"-ffinite-math-only"
"-fno-signed-zeros"
"-fno-trapping-math"
"-fno-fp-int-builtin-inexact"
"-fsingle-precision-constant"
"-Oz"
"-DNDEBUG"
"-Wno-unused-function"
"-Wno-type-limits"
"-Wno-deprecated-declarations"
"-fno-exceptions"
"-fno-rtti"
"-fdata-sections"
"-ffunction-sections"
"-Wl,--gc-sections,--strip-all"
"-flto=auto"
"-ffat-lto-objects"
