#ifndef CONFIG_USER_CONFIG_SODIUM_H_
#define CONFIG_USER_CONFIG_SODIUM_H_

#include "aether/config_consts.h"

#define AE_INSTRUMENT 1

#define AE_CRYPTO_ASYNC AE_SODIUM_BOX_SEAL
#define AE_CRYPTO_SYNC AE_CHACHA20_POLY1305
#define AE_SIGNATURE AE_ED25519
#define AE_KDF AE_SODIUM_KDF

#endif /* CONFIG_USER_CONFIG_SODIUM_H_ */
