/*
   * Copyright 2024 Aethernet Inc.
   *
   * Licensed under the Apache License, Version 2.0 (the "License");
   * you may not use this file except in compliance with the License.
   * You may obtain a copy of the License at
   *
   *     http://www.apache.org/licenses/LICENSE-2.0
   *
   * Unless required by applicable law or agreed to in writing, software
   * distributed under the License is distributed on an "AS IS" BASIS,
   * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   * See the License for the specific language governing permissions and
   * limitations under the License.
   */

  #ifndef AETHER_HEADERS_H_
  #define AETHER_HEADERS_H_

  #include "aether\adapter_registry.h"
  #include "aether\aether.h"
  #include "aether\aether_app.h"
  #include "aether\aether_tele.h"
  #include "aether\all.h"
  #include "aether\capi.h"
  #include "aether\client.h"
  #include "aether\cloud.h"
  #include "aether\common.h"
  #include "aether\config.h"
  #include "aether\config_consts.h"
  #include "aether\crc.h"
  #include "aether\crypto.h"
  #include "aether\env.h"
  #include "aether\global_ids.h"
  #include "aether\memory.h"
  #include "aether\memory_buffer.h"
  #include "aether\mstream.h"
  #include "aether\mstream_buffers.h"
  #include "aether\registration_cloud.h"
  #include "aether\server.h"
  #include "aether\server_keys.h"
  #include "aether\socket_initializer.h"
  #include "aether\type_traits.h"
  #include "aether\warning_disable.h"
  #include "aether\work_cloud.h"

  #include "aether\access_points\access_point.h"
  #include "aether\access_points\ethernet_access_point.h"
  #include "aether\access_points\modem_access_point.h"
  #include "aether\access_points\wifi_access_point.h"

  #include "aether\actions\action.h"
  #include "aether\actions\actions_queue.h"
  #include "aether\actions\action_context.h"
  #include "aether\actions\action_event_status.h"
  #include "aether\actions\action_processor.h"
  #include "aether\actions\action_ptr.h"
  #include "aether\actions\action_registry.h"
  #include "aether\actions\action_trigger.h"
  #include "aether\actions\gen_action.h"
  #include "aether\actions\notify_action.h"
  #include "aether\actions\pipeline.h"
  #include "aether\actions\promise_action.h"
  #include "aether\actions\repeatable_task.h"
  #include "aether\actions\task_queue.h"
  #include "aether\actions\timer_action.h"
  #include "aether\actions\update_status.h"

  #include "aether\adapters\adapter.h"
  #include "aether\adapters\adapter_tele.h"
  #include "aether\adapters\ethernet.h"
  #include "aether\adapters\modem_adapter.h"
  #include "aether\adapters\parent_modem.h"
  #include "aether\adapters\parent_wifi.h"
  #include "aether\adapters\proxy.h"
  #include "aether\adapters\wifi_adapter.h"

  #include "aether\aether_c\aether_capi.h"
  #include "aether\aether_c\c_conf.h"
  #include "aether\aether_c\c_errors.h"
  #include "aether\aether_c\c_types.h"
  #include "aether\aether_c\c_uid.h"
  #include "aether\aether_c\extern_c.h"

  #include "aether\ae_actions\ae_actions_tele.h"
  #include "aether\ae_actions\check_access_for_send_message.h"
  #include "aether\ae_actions\get_client_cloud.h"
  #include "aether\ae_actions\ping.h"
  #include "aether\ae_actions\select_client.h"
  #include "aether\ae_actions\telemetry.h"

  #include "aether\api_protocol\api_class_impl.h"
  #include "aether\api_protocol\api_context.h"
  #include "aether\api_protocol\api_message.h"
  #include "aether\api_protocol\api_method.h"
  #include "aether\api_protocol\api_promise_action.h"
  #include "aether\api_protocol\api_protocol.h"
  #include "aether\api_protocol\child_data.h"
  #include "aether\api_protocol\packet_builder.h"
  #include "aether\api_protocol\protocol_context.h"
  #include "aether\api_protocol\request_id.h"
  #include "aether\api_protocol\return_result_api.h"
  #include "aether\api_protocol\send_result.h"

  #include "aether\channels\channel.h"
  #include "aether\channels\channels_types.h"
  #include "aether\channels\channel_statistics.h"
  #include "aether\channels\ethernet_channel.h"
  #include "aether\channels\ethernet_transport_factory.h"
  #include "aether\channels\modem_channel.h"
  #include "aether\channels\wifi_channel.h"

  #include "aether\client_connections\client_connections_tele.h"
  #include "aether\client_connections\cloud_message_stream.h"

  #include "aether\client_messages\client_messages_tele.h"
  #include "aether\client_messages\p2p_message_stream.h"
  #include "aether\client_messages\p2p_message_stream_manager.h"
  #include "aether\client_messages\p2p_safe_message_stream.h"

  #include "aether\connection_manager\client_cloud_manager.h"
  #include "aether\connection_manager\client_connection_manager.h"
  #include "aether\connection_manager\iserver_connection_pool.h"
  #include "aether\connection_manager\iserver_priority_policy.h"
  #include "aether\connection_manager\server_connection_manager.h"
  #include "aether\connection_manager\server_connection_selector.h"

  #include "aether\crypto\async_crypto_provider.h"
  #include "aether\crypto\crypto_definitions.h"
  #include "aether\crypto\crypto_nonce.h"
  #include "aether\crypto\icrypto_provider.h"
  #include "aether\crypto\ikey_provider.h"
  #include "aether\crypto\key.h"
  #include "aether\crypto\key_gen.h"
  #include "aether\crypto\sign.h"
  #include "aether\crypto\signed_key.h"
  #include "aether\crypto\sync_crypto_provider.h"

  #include "aether\crypto\hydrogen\hydro_async_crypto_provider.h"
  #include "aether\crypto\hydrogen\hydro_sync_crypto_provider.h"

  #include "aether\crypto\sodium\sodium_async_crypto_provider.h"
  #include "aether\crypto\sodium\sodium_sync_crypto_provider.h"

  #include "aether\dns\dns_c_ares.h"
  #include "aether\dns\dns_resolve.h"
  #include "aether\dns\dns_tele.h"
  #include "aether\dns\esp32_dns_resolve.h"

  #include "aether\domain_storage\domain_storage_factory.h"
  #include "aether\domain_storage\domain_storage_tele.h"
  #include "aether\domain_storage\file_system_std_storage.h"
  #include "aether\domain_storage\ram_domain_storage.h"
  #include "aether\domain_storage\registrar_domain_storage.h"
  #include "aether\domain_storage\spifs_domain_storage.h"
  #include "aether\domain_storage\static_domain_storage.h"
  #include "aether\domain_storage\static_object_types.h"
  #include "aether\domain_storage\sync_domain_storage.h"

  #include "aether\events\cumulative_event.h"
  #include "aether\events\delegate.h"
  #include "aether\events\events.h"
  #include "aether\events\events_mt.h"
  #include "aether\events\event_deleter.h"
  #include "aether\events\event_handler.h"
  #include "aether\events\event_list.h"
  #include "aether\events\event_subscription.h"
  #include "aether\events\multi_subscription.h"

  #include "aether\format\default_formatters.h"
  #include "aether\format\format.h"
  #include "aether\format\formatter.h"
  #include "aether\format\format_impl.h"
  #include "aether\format\format_time.h"

  #include "aether\methods\server_descriptor.h"
  #include "aether\methods\telemetric.h"
  #include "aether\methods\uid_and_cloud.h"

  #include "aether\methods\client_api\client_root_api.h"
  #include "aether\methods\client_api\client_safe_api.h"

  #include "aether\methods\client_reg_api\client_global_reg_api.h"
  #include "aether\methods\client_reg_api\client_reg_api.h"
  #include "aether\methods\client_reg_api\client_reg_root_api.h"

  #include "aether\methods\server_reg_api\global_reg_server_api.h"
  #include "aether\methods\server_reg_api\root_api.h"
  #include "aether\methods\server_reg_api\server_registration_api.h"

  #include "aether\methods\work_server_api\authorized_api.h"
  #include "aether\methods\work_server_api\login_api.h"

  #include "aether\misc\defer.h"
  #include "aether\misc\from_chars.h"

  #include "aether\modems\bg95_at_modem.h"
  #include "aether\modems\exponent_time.h"
  #include "aether\modems\imodem_driver.h"
  #include "aether\modems\modems_tele.h"
  #include "aether\modems\modem_driver_types.h"
  #include "aether\modems\modem_factory.h"
  #include "aether\modems\sim7070_at_modem.h"
  #include "aether\modems\thingy91x_at_modem.h"

  #include "aether\obj\component_context.h"
  #include "aether\obj\domain.h"
  #include "aether\obj\dummy_obj.h"
  #include "aether\obj\idomain_storage.h"
  #include "aether\obj\obj.h"
  #include "aether\obj\obj_id.h"
  #include "aether\obj\obj_ptr.h"
  #include "aether\obj\obj_tele.h"
  #include "aether\obj\registrar.h"
  #include "aether\obj\registry.h"
  #include "aether\obj\version_iterator.h"

  #include "aether\poller\epoll_poller.h"
  #include "aether\poller\freertos_poller.h"
  #include "aether\poller\kqueue_poller.h"
  #include "aether\poller\poller.h"
  #include "aether\poller\poller_tele.h"
  #include "aether\poller\poller_types.h"
  #include "aether\poller\win_poller.h"

  #include "aether\ptr\ptr.h"
  #include "aether\ptr\ptr_management.h"
  #include "aether\ptr\ptr_view.h"
  #include "aether\ptr\rc_ptr.h"

  #include "aether\reflect\container_node_visitor.h"
  #include "aether\reflect\cycle_detector.h"
  #include "aether\reflect\domain_visitor.h"
  #include "aether\reflect\domain_visitor_impl.h"
  #include "aether\reflect\node_visitor.h"
  #include "aether\reflect\override_func.h"
  #include "aether\reflect\ptr_like_node_visitor.h"
  #include "aether\reflect\reflect.h"
  #include "aether\reflect\reflect_impl.h"
  #include "aether\reflect\reflect_node_visitor.h"
  #include "aether\reflect\type_index.h"

  #include "aether\registration\global_reg_server_stream.h"
  #include "aether\registration\proof_of_work.h"
  #include "aether\registration\registration.h"
  #include "aether\registration\registration_key_provider.h"
  #include "aether\registration\reg_server_stream.h"
  #include "aether\registration\root_server_select_stream.h"
  #include "aether\registration\root_server_stream.h"

  #include "aether\serial_ports\esp32_serial_port.h"
  #include "aether\serial_ports\iserial_port.h"
  #include "aether\serial_ports\serial_ports_tele.h"
  #include "aether\serial_ports\serial_port_factory.h"
  #include "aether\serial_ports\serial_port_types.h"
  #include "aether\serial_ports\unix_serial_port.h"
  #include "aether\serial_ports\win_serial_port.h"

  #include "aether\server_connections\channel_connection.h"
  #include "aether\server_connections\channel_manager.h"
  #include "aether\server_connections\channel_selection_stream.h"
  #include "aether\server_connections\client_server_connection.h"
  #include "aether\server_connections\client_to_server_stream.h"
  #include "aether\server_connections\iserver_connection_factory.h"
  #include "aether\server_connections\server_channel.h"
  #include "aether\server_connections\server_connection.h"

  #include "aether\stream_api\buffer_stream.h"
  #include "aether\stream_api\byte_gate.h"
  #include "aether\stream_api\crypto_gate.h"
  #include "aether\stream_api\debug_gate.h"
  #include "aether\stream_api\delegate_gate.h"
  #include "aether\stream_api\event_subscribe_gate.h"
  #include "aether\stream_api\gates_stream.h"
  #include "aether\stream_api\gate_trait.h"
  #include "aether\stream_api\istream.h"
  #include "aether\stream_api\protocol_gates.h"
  #include "aether\stream_api\safe_stream.h"
  #include "aether\stream_api\serialize_gate.h"
  #include "aether\stream_api\sized_packet_gate.h"
  #include "aether\stream_api\stream_api.h"
  #include "aether\stream_api\stream_splitter.h"
  #include "aether\stream_api\stream_write_action.h"
  #include "aether\stream_api\tied_gates.h"

  #include "aether\stream_api\safe_stream\receiving_chunk_list.h"
  #include "aether\stream_api\safe_stream\safe_stream_api.h"
  #include "aether\stream_api\safe_stream\safe_stream_config.h"
  #include "aether\stream_api\safe_stream\safe_stream_recv_action.h"
  #include "aether\stream_api\safe_stream\safe_stream_send_action.h"
  #include "aether\stream_api\safe_stream\safe_stream_types.h"
  #include "aether\stream_api\safe_stream\sending_chunk_list.h"
  #include "aether\stream_api\safe_stream\sending_data_action.h"
  #include "aether\stream_api\safe_stream\send_data_buffer.h"

  #include "aether\tele\collectors.h"
  #include "aether\tele\compile_option.h"
  #include "aether\tele\defines.h"
  #include "aether\tele\env_collectors.h"
  #include "aether\tele\itrap.h"
  #include "aether\tele\levels.h"
  #include "aether\tele\modules.h"
  #include "aether\tele\sink.h"
  #include "aether\tele\tags.h"
  #include "aether\tele\tele.h"
  #include "aether\tele\tele_init.h"

  #include "aether\tele\configs\config_provider.h"

  #include "aether\tele\env\compilation_options.h"
  #include "aether\tele\env\compiler.h"
  #include "aether\tele\env\cpu_architecture.h"
  #include "aether\tele\env\library_version.h"
  #include "aether\tele\env\platform_type.h"

  #include "aether\tele\traps\io_stream_traps.h"
  #include "aether\tele\traps\proxy_trap.h"
  #include "aether\tele\traps\statistics_trap.h"
  #include "aether\tele\traps\tele_statistics.h"

  #include "aether\transport\data_packet_collector.h"
  #include "aether\transport\socket_packet_queue_manager.h"
  #include "aether\transport\socket_packet_send_action.h"
  #include "aether\transport\transport_builder_action.h"
  #include "aether\transport\transport_tele.h"

  #include "aether\transport\actions\packet_send_action.h"

  #include "aether\transport\low_level\sockets\isocket.h"
  #include "aether\transport\low_level\sockets\lwip_socket.h"
  #include "aether\transport\low_level\sockets\lwip_tcp_socket.h"
  #include "aether\transport\low_level\sockets\lwip_udp_socket.h"
  #include "aether\transport\low_level\sockets\tcp_sockets_factory.h"
  #include "aether\transport\low_level\sockets\udp_sockets_factory.h"
  #include "aether\transport\low_level\sockets\unix_socket.h"
  #include "aether\transport\low_level\sockets\unix_tcp_socket.h"
  #include "aether\transport\low_level\sockets\unix_udp_socket.h"
  #include "aether\transport\low_level\sockets\win_socket.h"
  #include "aether\transport\low_level\sockets\win_tcp_socket.h"
  #include "aether\transport\low_level\sockets\win_udp_socket.h"

  #include "aether\transport\low_level\tcp\tcp.h"

  #include "aether\transport\low_level\udp\udp.h"

  #include "aether\transport\modems\modem_transport.h"
  #include "aether\transport\modems\send_queue_poller.h"

  #include "aether\types\address.h"
  #include "aether\types\address_parser.h"
  #include "aether\types\aligned_storage.h"
  #include "aether\types\data_buffer.h"
  #include "aether\types\literal_array.h"
  #include "aether\types\ring_buffer.h"
  #include "aether\types\span.h"
  #include "aether\types\state_machine.h"
  #include "aether\types\static_map.h"
  #include "aether\types\statistic_counter.h"
  #include "aether\types\type_list.h"
  #include "aether\types\uid.h"
  #include "aether\types\variant_type.h"

  #include "aether\wifi\esp_wifi_driver.h"
  #include "aether\wifi\wifi_driver.h"
  #include "aether\wifi\wifi_driver_factory.h"


  #endif // AETHER_HEADERS_H_
