"-DAE_PROJECT_VERSION=\"1.0.0\""
// User Tracking Measurement ID, must be a uint32 value
"-DUTM_ID=0"
// Path to user provided configuration header file
"-DUSER_CONFIG \"../../user_config_hydrogen.h\""
// Path to user provided saved state header file
// "-DFS_INIT \"../../file_system_init.h\""
// Build aether in distillation mode
"-DAE_DISTILLATION=1"
// Optinization flags
"-ffast-math"
"-fno-math-errno"
"-funsafe-math-optimizations"
"-fassociative-math"
"-freciprocal-math"
"-ffinite-math-only"
"-fno-signed-zeros"
"-fno-trapping-math"
"-fno-fp-int-builtin-inexact"
"-fsingle-precision-constant"
"-Oz"
"-DNDEBUG"
"-Wno-unused-function"
"-Wno-type-limits"
"-Wno-deprecated-declarations"
"-fno-exceptions"
"-fno-rtti"
"-fdata-sections"
"-ffunction-sections"
"-Wl,--gc-sections,--strip-all"
"-flto=auto"
"-ffat-lto-objects"
