"-DAE_PROJECT_VERSION=\"1.0.0\""
"-DComment_USER_CONFIG=\"Path to user provided configuration header file\""
"-DUSER_CONFIG=\"../config/user_config_hydrogen.h\""
"-DComment_FS_INIT=\"Path to user provided saved state header file\""
"-DComment_AE_DISTILLATION=\"Build aether in distillation mode\""
"-DAE_DISTILLATION=1"
"-DComment_flags=\"Optimization flags\""
"-DNDEBUG"
"-Oz"
"-ffast-math"
"-fno-math-errno"
"-funsafe-math-optimizations"
"-fassociative-math"
"-freciprocal-math"
"-ffinite-math-only"
"-fno-signed-zeros"
"-fno-trapping-math"
"-fno-fp-int-builtin-inexact"
"-fsingle-precision-constant"
"-Wno-unused-function"
"-Wno-type-limits"
"-Wno-deprecated-declarations"
"-fno-exceptions"
"-fno-rtti"
"-fdata-sections"
"-ffunction-sections"
"-Wl,--gc-sections,--strip-all"
"-flto=auto"
"-ffat-lto-objects"